@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name RecadosController
GET {{baseUrl}}

###
# QUERY URL
GET {{baseUrl}}/???/
?limit=10
&offset=10
Authorization: 'bearer token'

###
# CRIA -> POST
POST {{baseUrl}}/doc-protesto/
Content-Type: application/json

{
    "data_apresentacao": "2025-05-07T03:17:00.000Z",
    "num_distribuicao": "235",
    "data_distribuicao": "2025-05-07T03:17:00.000Z",
    "cart_protesto": "1",
    "num_titulo": "54654",
    "vencimento": "2024-10-22T03:15:00.000Z"
}

###
 

 ###
##EXIBE TODOS
{{baseUrl}}/user/

###
##CRIA USER
POST {{baseUrl}}/user/
Content-Type: application/json

{
   "nome":"user1",
   "email": "emailuser1@email.com",
   "contato": "41997653623",
   "password": "12345",
   "admin": true
}


###
## UPDATE
PATCH  {{baseUrl}}/user/4/
Content-Type: application/json

{
   "password": "duarte30"
}


###   
## DELETA
DELETE {{baseUrl}}/user/3/



###
## AUTH
POST {{baseUrl}}/auth/